version: 2.1
workflows:
  test_and_lint:
    jobs:
      - test_and_lint

jobs:
  test_and_lint:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libappindicator1 fonts-liberation
            export CHROME_BIN=/usr/bin/google-chrome
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome*.deb

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: Bundle Install
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Create DB
          command: bin/rails db:create db:schema:load --trace RAILS_ENV=test
      - run:
          name: Run Tests
          command: bundle exec rspec RAILS_ENV=test
      - store_test_results:
          path: /tmp/test-results
      - run:
          name: Run Lint
          when: always
          command: bundle exec rubocop
