default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: el_traning_development

test:
  <<: *default
  database: el_traning_test

production:
  <<: *default
  database: el_traning_prodction
  username: <%= ENV['APP_DATABASE_USERNAME'] %>
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
